// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

// Linux distributions. Each row contains a Linux distro with a version.
type Distro struct {
	ID      int64
	Name    string
	Version string
}

// Major versions of packages
type MajorVersion struct {
	ID          int64
	PackageID   int64
	VersionName string
	ReleaseDate time.Time
}

// Package information that is shared across distributions
type Package struct {
	ID            int64
	HumanName     string
	Name          string
	LatestVersion int64
	Description   string
	Keywords      []string
	Homepage      string
	Developer     []string
}

// Package variants for each distro
type Variation struct {
	ID          int64
	PackageID   int64
	DistroID    int64
	Name        string
	Version     int64
	PackageUrl  string
	DownloadUrl string
}

// Minor versions of packages
type Version struct {
	ID             int64
	MajorVersionID int64
	VersionName    string
	ReleaseDate    time.Time
}
