CREATE TABLE distro
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    TEXT NOT NULL DEFAULT '',
    version TEXT NOT NULL DEFAULT ''
);

COMMENT ON TABLE distro IS 'Linux distributions. Each row contains a Linux distro with a version.';

CREATE TABLE package
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    human_name     TEXT NOT NULL DEFAULT '',
    name           TEXT NOT NULL DEFAULT '',
    latest_version BIGINT NOT NULL DEFAULT 0,
    description    TEXT NOT NULL DEFAULT '',
    keywords       TEXT[] NOT NULL DEFAULT '{}',
    homepage       TEXT NOT NULL DEFAULT '',
    developer      TEXT[] NOT NULL DEFAULT '{}'
);

COMMENT ON TABLE package IS 'Package information that is shared across distributions';

CREATE TABLE major_version
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id   BIGINT NOT NULL,
    version_name TEXT NOT NULL DEFAULT '',
    release_date DATE NOT NULL DEFAULT CURRENT_DATE
);

COMMENT ON TABLE major_version IS 'Major versions of packages';

CREATE TABLE version
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    major_version_id BIGINT NOT NULL,
    version_name     TEXT NOT NULL DEFAULT '',
    release_date     DATE NOT NULL DEFAULT CURRENT_DATE
);

COMMENT ON TABLE version IS 'Minor versions of packages';

CREATE TABLE variation
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id   BIGINT NOT NULL,
    distro_id    BIGINT NOT NULL,
    name         TEXT NOT NULL DEFAULT '',
    version      BIGINT NOT NULL DEFAULT 0,
    package_url  TEXT NOT NULL DEFAULT '',
    download_url TEXT NOT NULL DEFAULT ''
);

COMMENT ON TABLE variation IS 'Package variants for each distro';

ALTER TABLE major_version
    ADD CONSTRAINT fk_major_version_package
        FOREIGN KEY (package_id) REFERENCES package (id);

ALTER TABLE version
    ADD CONSTRAINT fk_version_major_version
        FOREIGN KEY (major_version_id) REFERENCES major_version (id);

ALTER TABLE variation
    ADD CONSTRAINT fk_variation_package
        FOREIGN KEY (package_id) REFERENCES package (id),
    ADD CONSTRAINT fk_variation_distro
        FOREIGN KEY (distro_id) REFERENCES distro (id);

CREATE INDEX idx_major_version_package_id ON major_version (package_id);
CREATE INDEX idx_version_major_version_id ON version (major_version_id);
CREATE INDEX idx_variation_package_id ON variation (package_id);
CREATE INDEX idx_variation_distro_id ON variation (distro_id);

-- Extension
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
