// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Linux distributions. Each row contains a Linux distro with a version.
type Distro struct {
	ID      int64
	Name    string
	Version pgtype.Text
}

// Major versions of packages
type MajorVersion struct {
	ID          int64
	PackageID   int64
	VersionName pgtype.Text
	ReleaseDate pgtype.Date
}

// Package information that is shared across distributions
type Package struct {
	ID            int64
	HumanName     string
	Name          pgtype.Text
	LatestVersion pgtype.Int8
	Description   pgtype.Text
	Keywords      []string
	Homepage      pgtype.Text
	Developer     []string
}

// Package variants for each distro
type Variation struct {
	ID          int64
	PackageID   int64
	DistroID    int64
	Name        string
	Version     pgtype.Int8
	PackageUrl  pgtype.Text
	DownloadUrl pgtype.Text
}

// Minor versions of packages
type Version struct {
	ID             int64
	MajorVersionID int64
	VersionName    pgtype.Text
	ReleaseDate    pgtype.Date
}
